# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='report.proto',
  package='report',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0creport.proto\x12\x06report\"3\n\x13\x43reateReportRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06layout\x18\x02 \x01(\t\"\x1e\n\x10GetReportRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12ListReportsRequest\"6\n\x13ListReportsResponse\x12\x1f\n\x07reports\x18\x01 \x03(\x0b\x32\x0e.report.Report\"?\n\x13UpdateReportRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06layout\x18\x03 \x01(\t\"!\n\x13\x44\x65leteReportRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x06Report\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06layout\x18\x03 \x01(\t2\xdd\x02\n\rReportService\x12=\n\x0c\x43reateReport\x12\x1b.report.CreateReportRequest\x1a\x0e.report.Report\"\x00\x12\x37\n\tGetReport\x12\x18.report.GetReportRequest\x1a\x0e.report.Report\"\x00\x12H\n\x0bListReports\x12\x1a.report.ListReportsRequest\x1a\x1b.report.ListReportsResponse\"\x00\x12=\n\x0cUpdateReport\x12\x1b.report.UpdateReportRequest\x1a\x0e.report.Report\"\x00\x12K\n\x0c\x44\x65leteReport\x12\x1b.report.DeleteReportRequest\x1a\x1c.report.DeleteReportResponse\"\x00\x62\x06proto3'
)




_CREATEREPORTREQUEST = _descriptor.Descriptor(
  name='CreateReportRequest',
  full_name='report.CreateReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='report.CreateReportRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layout', full_name='report.CreateReportRequest.layout', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=75,
)


_GETREPORTREQUEST = _descriptor.Descriptor(
  name='GetReportRequest',
  full_name='report.GetReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='report.GetReportRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=107,
)


_LISTREPORTSREQUEST = _descriptor.Descriptor(
  name='ListReportsRequest',
  full_name='report.ListReportsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=129,
)


_LISTREPORTSRESPONSE = _descriptor.Descriptor(
  name='ListReportsResponse',
  full_name='report.ListReportsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reports', full_name='report.ListReportsResponse.reports', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=185,
)


_UPDATEREPORTREQUEST = _descriptor.Descriptor(
  name='UpdateReportRequest',
  full_name='report.UpdateReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='report.UpdateReportRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='report.UpdateReportRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layout', full_name='report.UpdateReportRequest.layout', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=250,
)


_DELETEREPORTREQUEST = _descriptor.Descriptor(
  name='DeleteReportRequest',
  full_name='report.DeleteReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='report.DeleteReportRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=285,
)


_DELETEREPORTRESPONSE = _descriptor.Descriptor(
  name='DeleteReportResponse',
  full_name='report.DeleteReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='report.DeleteReportResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=326,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='report.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='report.Report.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='report.Report.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layout', full_name='report.Report.layout', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=378,
)

_LISTREPORTSRESPONSE.fields_by_name['reports'].message_type = _REPORT
DESCRIPTOR.message_types_by_name['CreateReportRequest'] = _CREATEREPORTREQUEST
DESCRIPTOR.message_types_by_name['GetReportRequest'] = _GETREPORTREQUEST
DESCRIPTOR.message_types_by_name['ListReportsRequest'] = _LISTREPORTSREQUEST
DESCRIPTOR.message_types_by_name['ListReportsResponse'] = _LISTREPORTSRESPONSE
DESCRIPTOR.message_types_by_name['UpdateReportRequest'] = _UPDATEREPORTREQUEST
DESCRIPTOR.message_types_by_name['DeleteReportRequest'] = _DELETEREPORTREQUEST
DESCRIPTOR.message_types_by_name['DeleteReportResponse'] = _DELETEREPORTRESPONSE
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateReportRequest = _reflection.GeneratedProtocolMessageType('CreateReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPORTREQUEST,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.CreateReportRequest)
  })
_sym_db.RegisterMessage(CreateReportRequest)

GetReportRequest = _reflection.GeneratedProtocolMessageType('GetReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREPORTREQUEST,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.GetReportRequest)
  })
_sym_db.RegisterMessage(GetReportRequest)

ListReportsRequest = _reflection.GeneratedProtocolMessageType('ListReportsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREPORTSREQUEST,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.ListReportsRequest)
  })
_sym_db.RegisterMessage(ListReportsRequest)

ListReportsResponse = _reflection.GeneratedProtocolMessageType('ListReportsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTREPORTSRESPONSE,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.ListReportsResponse)
  })
_sym_db.RegisterMessage(ListReportsResponse)

UpdateReportRequest = _reflection.GeneratedProtocolMessageType('UpdateReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREPORTREQUEST,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.UpdateReportRequest)
  })
_sym_db.RegisterMessage(UpdateReportRequest)

DeleteReportRequest = _reflection.GeneratedProtocolMessageType('DeleteReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREPORTREQUEST,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.DeleteReportRequest)
  })
_sym_db.RegisterMessage(DeleteReportRequest)

DeleteReportResponse = _reflection.GeneratedProtocolMessageType('DeleteReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREPORTRESPONSE,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.DeleteReportResponse)
  })
_sym_db.RegisterMessage(DeleteReportResponse)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.Report)
  })
_sym_db.RegisterMessage(Report)



_REPORTSERVICE = _descriptor.ServiceDescriptor(
  name='ReportService',
  full_name='report.ReportService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=381,
  serialized_end=730,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateReport',
    full_name='report.ReportService.CreateReport',
    index=0,
    containing_service=None,
    input_type=_CREATEREPORTREQUEST,
    output_type=_REPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetReport',
    full_name='report.ReportService.GetReport',
    index=1,
    containing_service=None,
    input_type=_GETREPORTREQUEST,
    output_type=_REPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListReports',
    full_name='report.ReportService.ListReports',
    index=2,
    containing_service=None,
    input_type=_LISTREPORTSREQUEST,
    output_type=_LISTREPORTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateReport',
    full_name='report.ReportService.UpdateReport',
    index=3,
    containing_service=None,
    input_type=_UPDATEREPORTREQUEST,
    output_type=_REPORT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteReport',
    full_name='report.ReportService.DeleteReport',
    index=4,
    containing_service=None,
    input_type=_DELETEREPORTREQUEST,
    output_type=_DELETEREPORTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPORTSERVICE)

DESCRIPTOR.services_by_name['ReportService'] = _REPORTSERVICE

# @@protoc_insertion_point(module_scope)
